### ISSUE TITLE
'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/xxx/yyy/yup/ios/Pods/TrustDecisionCaptcha/libTDCaptcha.a and /Users/xxx/yyy/yup/ios/Pods/TrustDecisionPro/TDMobRisk.framework)

### ISSUE THREAD

**Issue by axyh** [trustdecision/trustdevice-pro-flutter#5]
'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/xxx/yyy/yup/ios/Pods/TrustDecisionCaptcha/libTDCaptcha.a and /Users/xxx/yyy/yup/ios/Pods/TrustDecisionPro/TDMobRisk.framework)

**Comment by iOSPrincekin** [comment]
please use  trustdevice_pro_plugin: ^1.2.3
