### ISSUE TITLE
Open app crash

### ISSUE THREAD

**Issue by HatsuneMikuV** [trustdecision/trustdevice-pro-flutter#7]
Can't show file for stack frame : <DBGLLDBStackFrame: 0x3410c5380> - stackNumber:7 - name:_tdmr_73a52058f17b5e3f5c7bd09fa3f61597. The file path does not exist on the file system: /Users/tdfaker/.jenkins/workspace/TDMobRisk/TDMobRisk/TDMobRiskManager.m

![image](https://github.com/user-attachments/assets/6c35f393-fdd2-4f87-b612-2171b8a3509c)

```

trustdevice_pro_plugin: ^1.3.3

s.dependency 'TrustDecisionLiveness'

```

There is no problem running with the demo, but once you set your own appkey, you will inevitably get an error

**Comment by iOSPrincekin** [comment]
One of the initialization parameters was incorrectly passed. Please contact our operations or visit https://trustdecision.com to contact technical support.
