### ISSUE TITLE
Upload to App Store Connect failed

### ISSUE THREAD

**Issue by 106271** [trustdecision/trustdevice-pro-flutter#8]
"<IDEDistributionIssue: severity(error), error(Error Domain=ContentDelivery Code=90668 \"Asset validation failed\" UserInfo={IDEDistributionIssueSeverity=3, NSLocalizedDescription=Asset validation failed, NSLocalizedRecoverySuggestion=Invalid Bundle Executable. The executable file 'Runner.app/Frameworks/TDCorePlugin.framework/TDCorePlugin' contains incomplete bitcode. To compile binaries with complete bitcode, open Xcode and choose Archive in the Product menu. (ID: bff37d7c-4470-4b99-a3dd-11654d5b3394)})>" 
![截屏2024-12-25 11 10 10](https://github.com/user-attachments/assets/b7e179d3-cfa6-4f5d-be27-f34ad657c524)

 --- Xcode ---
ContentDelivery version 2.160.11 (16011)
Macintosh; macOS 15.1 24B83 (arm64)
Free disk space: 15.38GB

**Comment by iOSPrincekin** [comment]
cd the podfile directory, and exec ' pod install --repo-update' , then the latest TrustDecisionPro version number should be 4.3.1.3 in the pods directory!

**Comment by 106271** [comment]
Thanks to reply, what about  'TrustDecisionLiveness' latest version is ?

**Comment by iOSPrincekin** [comment]
delete the Podfile.lock file and the pods directory, and exec ' pod install --repo-update' , then check Pods/TrustDecisionPro/TDMobRisk.xcframework/ios-arm64_armv7/TDMobRisk.framework/Headers/TDMobRiskManager.h file TDMOBRISK_SDK_VERSION string,it should be '#define TDMOBRISK_SDK_VERSION @"4.3.1.3" '
